#!/usr/bin/env python

# set server timezone in UTC before time module imported
__import__('os').environ['TZ'] = 'UTC'
__import__('pkg_resources').declare_namespace('odoo.addons')

# XML-RPC utf8 monkeypatch
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

import odoo

if __name__ == "__main__":
    odoo.cli.main()
